#!/bin/bash
SERVER_NAME=orange
DIRECTORY_NAME=frozen_speech
cargo build
(cd contents && ~/rustc_target/debug/frozen_speech)
ssh $SERVER_NAME << EOF
git init $DIRECTORY_NAME
cd $DIRECTORY_NAME
git config receive.denyCurrentBranch updateInstead
EOF
git remote add deployment $SERVER_NAME:$DIRECTORY_NAME
git push deployment
ssh $SERVER_NAME << EOF
cd $DIRECTORY_NAME
docker build --progress=plain . -t $DIRECTORY_NAME
docker rm --force $DIRECTORY_NAME
docker run -d -p 8009:80 --name $DIRECTORY_NAME --restart unless-stopped $DIRECTORY_NAME
EOF
